name: Frontend CI

on:
  push:
    branches: [main, develop]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-ci.yml'
      - '.github/actions/setup-frontend/**'
  pull_request:
    branches: [main, develop]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-ci.yml'
      - '.github/actions/setup-frontend/**'

jobs:
  lint:
    name: Lint & Type Check
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - uses: ./.github/actions/setup-frontend

      - name: Run ESLint
        run: npm run lint
        continue-on-error: true  # Temporary: Remove after fixing existing issues (see GitHub issues)

      - name: Run TypeScript type check
        run: npx tsc --noEmit

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - uses: ./.github/actions/setup-frontend

      - name: Run tests
        run: npm test

  security:
    name: Security Scan
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - uses: ./.github/actions/setup-frontend

      - name: Run npm audit
        run: npm audit --audit-level=high
        continue-on-error: true  # Temporary: Create audit exceptions file, then remove

      - name: Check for secrets
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./frontend
          base: ${{ github.event.repository.default_branch }}
          head: HEAD

  build:
    name: Build & Verify
    runs-on: ubuntu-latest
    needs: [lint, test, security]
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - uses: ./.github/actions/setup-frontend

      - name: Build application
        run: npm run build

      - name: Verify build output
        run: |
          echo "Checking build output..."
          if [ -d "dist" ]; then
            echo "✅ Build successful - dist directory exists"
            ls -lh dist/
          else
            echo "❌ Build failed - dist directory not found"
            exit 1
          fi

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build-${{ github.sha }}
          path: |
            frontend/dist/
            frontend/package.json
            frontend/package-lock.json
          retention-days: 7
